version: "3.9"
services:
  postgis:
    container_name: gis_postgis
    build: ./postgis
    image: gis_postgis
    #restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    secrets:
      - postgres-passwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  shiny:
    # profiles: ["dev"]
    container_name: gis_shiny
    build: ./shiny
    image: gis_shiny
    #restart: always
    volumes:
      - shiny_logs:/var/log/shiny-server
      # TODO: package app apropriatly for non-development
      - ./shiny/apps/:/home/rstudio/apps
    # TODO: update user to non-root after figuring out s6 permissions issue:
    #   https://github.com/rocker-org/rocker-versioned2/issues/105
    #user: shiny
    ports:
      - 3838:3838
      - 8787:8787
    # TODO: make password more secure for actual release
    environment:
      - PASSWORD=${RSTUDIO_PASSWD:?set RSTUDIO_PASSWD in .env}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    secrets:
      - postgres-passwd

secrets:
  postgres-passwd:
    file: ./postgis/postgres-passwd

volumes:
  pgdata:
    name: gis_pgdata
  shiny_logs:
    name: gis_shiny_logs
